export const TYPES_BLEND = {
    ADD_TO_BLEND: "ADD_TO_BLEND",
    REMOVE_FROM_BLEND: "REMOVE_FROM_BLEND",
    CLEAR_BLEND: "CLEAR_BLEND",
    READ_ALL_DATA: "READ_ALL_DATA",
    NO_DATA_FOUND: "NO_DATA_FOUND",
    FULL: "FULL",


}